[target.xtensa-{{ mcu }}-none-elf]
runner = "espflash --monitor"

[build]
rustflags = [
{%- if mcu == "esp32s2" %}
  # Enable the atomic codegen option for Xtensa
  "-C", "target-feature=+s32c1i",
{% endif -%}

{% if mcu == "esp32s2" %}
  # Tell the `core` library that we have atomics, even though it's not
  # specified in the target definition
  "--cfg", "target_has_atomic_load_store",
  "--cfg", 'target_has_atomic_load_store="8"',
  "--cfg", 'target_has_atomic_load_store="16"',
  "--cfg", 'target_has_atomic_load_store="32"',
  "--cfg", 'target_has_atomic_load_store="ptr"',
  "--cfg", "target_has_atomic",
  "--cfg", 'target_has_atomic="8"',
  "--cfg", 'target_has_atomic="16"',
  "--cfg", 'target_has_atomic="32"',
  "--cfg", 'target_has_atomic="ptr"',
{% endif %}
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x"
]

target = "xtensa-{{ mcu }}-none-elf"

[unstable]
{% if alloc -%}
build-std = ["alloc", "core"]
{%- else -%}
build-std = ["core"]
{%- endif %}
