name: CI
on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  schedule:
    - cron: "50 7 * * *"

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  rust-checks:
    name: cargo ${{ matrix.action.command }} - ${{ matrix.board.target }} (alloc=${{ matrix.alloc }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - target: esp32
            arch: xtensa
          - target: esp32s2
            arch: xtensa
          - target: esp32s3
            arch: xtensa
          - target: esp32c2
            arch: riscv
          - target: esp32c3
            arch: riscv
        alloc: ["true", "false"]
        action:
          - command: build
            args: --release
          - command: fmt
            args: -- --check
          - command: clippy
            args: --no-deps -- -D warnings -A clippy::empty_loop -A dead_code
    steps:
      - uses: actions/checkout@v3
        with:
          path: /home/runner/work/esp-template/esp-template/github-esp-template
      - name: Setup | Rust
        if: matrix.board.arch == 'riscv'
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: clippy, rustfmt, rust-src
      - name: Setup | Rust
        if: matrix.board.arch == 'xtensa'
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: ${{ matrix.board.target }}
          ldproxy: false
      - uses: Swatinem/rust-cache@v2
      - name: Setup | cargo-generate (binaries)
        id: binaries
        continue-on-error: true
        run: |
          sudo curl -L "https://github.com/cargo-generate/cargo-generate/releases/latest/download/cargo-generate-$(git ls-remote --refs --sort="version:refname" --tags "https://github.com/cargo-generate/cargo-generate" | cut -d/ -f3- | tail -n1)-x86_64-unknown-linux-gnu.tar.gz" -o "/home/runner/.cargo/bin/cargo-generate.tar.gz"
          tar xf "/home/runner/.cargo/bin/cargo-generate.tar.gz" -C /home/runner/.cargo/bin
          chmod u+x /home/runner/.cargo/bin/cargo-generate
      - name: Setup | cargo-generate (cargo)
        if: steps.binaries.outcome != 'success'
        run: cargo install cargo-generate
      - name: Generate
        run: cargo generate --path /home/runner/work/esp-template/esp-template/github-esp-template ${{ matrix.board.arch }} --name test --vcs none --silent -d mcu=${{ matrix.board.target }} -d devcontainer=false -d alloc=${{ matrix.alloc }}
      - name: cargo ${{ matrix.action.command }}
        run: cd test; cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
  docker-checks:
    name: Build project using the generated Dockerfile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - target: esp32
            arch: xtensa
          - target: esp32s2
            arch: xtensa
          - target: esp32s3
            arch: xtensa
          - target: esp32c2
            arch: riscv
          - target: esp32c3
            arch: riscv
    steps:
      - uses: actions/checkout@v3
        with:
          path: /home/runner/work/esp-template/esp-template/github-esp-template
      - uses: Swatinem/rust-cache@v2
      - name: Setup | cargo-generate (binaries)
        id: binaries
        continue-on-error: true
        run: |
          sudo curl -L "https://github.com/cargo-generate/cargo-generate/releases/latest/download/cargo-generate-$(git ls-remote --refs --sort="version:refname" --tags "https://github.com/cargo-generate/cargo-generate" | cut -d/ -f3- | tail -n1)-x86_64-unknown-linux-gnu.tar.gz" -o "/home/runner/.cargo/bin/cargo-generate.tar.gz"
          tar xf "/home/runner/.cargo/bin/cargo-generate.tar.gz" -C /home/runner/.cargo/bin
          chmod u+x /home/runner/.cargo/bin/cargo-generate
      - name: Setup | cargo-generate (cargo)
        if: steps.binaries.outcome != 'success'
        run: cargo install cargo-generate
      - name: Generate
        run: cargo generate --path /home/runner/work/esp-template/esp-template/github-esp-template ${{ matrix.board.arch }} --name test-${{ matrix.board.target }} --vcs none --silent -d mcu=${{ matrix.board.target }} -d devcontainer=true -d alloc=false
      - name: Update ownership
        run: |
          sudo chown 1000:1000 -R test-${{ matrix.board.target }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: test-${{ matrix.board.target }}:latest
          build-args: ESP_BOARD=${{ matrix.board.target }}
          file: test-${{ matrix.board.target }}/.devcontainer/Dockerfile
          push: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the build process with Docker (Xtensa)
        if: matrix.board.arch == 'xtensa'
        uses: addnab/docker-run-action@v3
        with:
          image: test-${{ matrix.board.target }}:latest
          options: -u esp -v ${{ github.workspace }}/test-${{ matrix.board.target }}:/home/esp/test-${{ matrix.board.target }}
          run: |
            cd /home/esp/test-${{ matrix.board.target }}
            bash -c 'source /home/esp/export-esp.sh && cargo build'
      - name: Run the build process with Docker (RISC-V)
        if: matrix.board.arch == 'riscv'
        uses: addnab/docker-run-action@v3
        with:
          image: test-${{ matrix.board.target }}:latest
          options: -u esp -v ${{ github.workspace }}/test-${{ matrix.board.target }}:/home/esp/test-${{ matrix.board.target }}
          run: |
            cd /home/esp/test-${{ matrix.board.target }}
            bash -c cargo build'
